# Vistazos a la base de datos

In [1]:
import pandas as pd  # noqa: F401
import sys
import os

from importlib import reload

# Asegurar que el path apunte a la raíz para encontrar el paquete 'src'
root_path = os.path.abspath(os.path.join(os.getcwd(), '..'))
if root_path not in sys.path:
    sys.path.append(root_path)

In [ ]:
from src.reports import saldos

saldos()

In [19]:
from src.database import engine

df = pd.read_sql("comisiones", engine, "id")

df

Empty DataFrame
Columns: [socio_originador_id, socio_comisionista_id, fecha, colocacion_originador, colocacion_comisionista, cobranza_originador, cobranza_comisionista, comision, comision_originador, comision_comisionista]
Index: []

In [9]:
df

,credito_id,nro_cuota,fecha_vencimiento,capital,interes,iva,estado,estado_cesion
id,,,,,,,,
1,1,1,2022-09-20,2314.15,3992.97,0.00,CANCELADA,NO_VENDIDA
2,1,2,2022-10-20,2463.74,3869.35,0.00,CANCELADA,NO_VENDIDA
3,1,3,2022-11-20,2622.99,3737.73,0.00,CANCELADA,NO_VENDIDA
4,1,4,2022-12-20,2792.54,3597.61,0.00,CANCELADA,NO_VENDIDA
5,1,5,2023-01-20,2973.05,3448.43,0.00,CANCELADA,NO_VENDIDA
...,...,...,...,...,...,...,...,...
8122,656,20,2028-02-28,14259.78,8381.56,1760.13,PENDIENTE,NO_VENDIDA
8123,656,21,2028-03-28,15877.18,7044.87,1479.42,PENDIENTE,NO_VENDIDA
8124,656,22,2028-04-28,17678.04,5556.55,1166.88,PENDIENTE,NO_VENDIDA
8125,656,23,2028-05-28,19683.15,3899.44,818.88,PENDIENTE,NO_VENDIDA
8126,656,24,2028-06-28,21915.69,2054.36,431.42,PENDIENTE,NO_VENDIDA